// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"github.com/ArifulProtik/gograph-notes/ent"
)

type Login struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

type LoginRes struct {
	User         *ent.User `json:"user"`
	Accestoken   *string   `json:"accestoken"`
	RefreshToken *string   `json:"refreshToken"`
}

type NewUser struct {
	Name     string `json:"name"`
	Username string `json:"username"`
	Email    string `json:"email"`
	Password string `json:"password"`
}
