// Code generated by entc, DO NOT EDIT.

package ent

import "context"

func (n *Notes) Author(ctx context.Context) (*User, error) {
	result, err := n.Edges.AuthorOrErr()
	if IsNotLoaded(err) {
		result, err = n.QueryAuthor().Only(ctx)
	}
	return result, MaskNotFound(err)
}

func (u *User) Notes(ctx context.Context) ([]*Notes, error) {
	result, err := u.Edges.NotesOrErr()
	if IsNotLoaded(err) {
		result, err = u.QueryNotes().All(ctx)
	}
	return result, err
}
