// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/ArifulProtik/gograph-notes/ent/notes"
	"github.com/ArifulProtik/gograph-notes/ent/predicate"
	"github.com/ArifulProtik/gograph-notes/ent/user"
	"github.com/google/uuid"
)

// NotesUpdate is the builder for updating Notes entities.
type NotesUpdate struct {
	config
	hooks    []Hook
	mutation *NotesMutation
}

// Where appends a list predicates to the NotesUpdate builder.
func (nu *NotesUpdate) Where(ps ...predicate.Notes) *NotesUpdate {
	nu.mutation.Where(ps...)
	return nu
}

// SetTitle sets the "title" field.
func (nu *NotesUpdate) SetTitle(s string) *NotesUpdate {
	nu.mutation.SetTitle(s)
	return nu
}

// SetBody sets the "body" field.
func (nu *NotesUpdate) SetBody(s string) *NotesUpdate {
	nu.mutation.SetBody(s)
	return nu
}

// SetSlug sets the "slug" field.
func (nu *NotesUpdate) SetSlug(s string) *NotesUpdate {
	nu.mutation.SetSlug(s)
	return nu
}

// SetTags sets the "tags" field.
func (nu *NotesUpdate) SetTags(s []string) *NotesUpdate {
	nu.mutation.SetTags(s)
	return nu
}

// SetCreatedAt sets the "created_at" field.
func (nu *NotesUpdate) SetCreatedAt(t time.Time) *NotesUpdate {
	nu.mutation.SetCreatedAt(t)
	return nu
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (nu *NotesUpdate) SetNillableCreatedAt(t *time.Time) *NotesUpdate {
	if t != nil {
		nu.SetCreatedAt(*t)
	}
	return nu
}

// SetAuthorID sets the "author" edge to the User entity by ID.
func (nu *NotesUpdate) SetAuthorID(id uuid.UUID) *NotesUpdate {
	nu.mutation.SetAuthorID(id)
	return nu
}

// SetNillableAuthorID sets the "author" edge to the User entity by ID if the given value is not nil.
func (nu *NotesUpdate) SetNillableAuthorID(id *uuid.UUID) *NotesUpdate {
	if id != nil {
		nu = nu.SetAuthorID(*id)
	}
	return nu
}

// SetAuthor sets the "author" edge to the User entity.
func (nu *NotesUpdate) SetAuthor(u *User) *NotesUpdate {
	return nu.SetAuthorID(u.ID)
}

// Mutation returns the NotesMutation object of the builder.
func (nu *NotesUpdate) Mutation() *NotesMutation {
	return nu.mutation
}

// ClearAuthor clears the "author" edge to the User entity.
func (nu *NotesUpdate) ClearAuthor() *NotesUpdate {
	nu.mutation.ClearAuthor()
	return nu
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (nu *NotesUpdate) Save(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(nu.hooks) == 0 {
		if err = nu.check(); err != nil {
			return 0, err
		}
		affected, err = nu.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*NotesMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			if err = nu.check(); err != nil {
				return 0, err
			}
			nu.mutation = mutation
			affected, err = nu.sqlSave(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(nu.hooks) - 1; i >= 0; i-- {
			if nu.hooks[i] == nil {
				return 0, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = nu.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, nu.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// SaveX is like Save, but panics if an error occurs.
func (nu *NotesUpdate) SaveX(ctx context.Context) int {
	affected, err := nu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (nu *NotesUpdate) Exec(ctx context.Context) error {
	_, err := nu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (nu *NotesUpdate) ExecX(ctx context.Context) {
	if err := nu.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (nu *NotesUpdate) check() error {
	if v, ok := nu.mutation.Title(); ok {
		if err := notes.TitleValidator(v); err != nil {
			return &ValidationError{Name: "title", err: fmt.Errorf("ent: validator failed for field \"title\": %w", err)}
		}
	}
	if v, ok := nu.mutation.Body(); ok {
		if err := notes.BodyValidator(v); err != nil {
			return &ValidationError{Name: "body", err: fmt.Errorf("ent: validator failed for field \"body\": %w", err)}
		}
	}
	if v, ok := nu.mutation.Slug(); ok {
		if err := notes.SlugValidator(v); err != nil {
			return &ValidationError{Name: "slug", err: fmt.Errorf("ent: validator failed for field \"slug\": %w", err)}
		}
	}
	return nil
}

func (nu *NotesUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   notes.Table,
			Columns: notes.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeUUID,
				Column: notes.FieldID,
			},
		},
	}
	if ps := nu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := nu.mutation.Title(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: notes.FieldTitle,
		})
	}
	if value, ok := nu.mutation.Body(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: notes.FieldBody,
		})
	}
	if value, ok := nu.mutation.Slug(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: notes.FieldSlug,
		})
	}
	if value, ok := nu.mutation.Tags(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeJSON,
			Value:  value,
			Column: notes.FieldTags,
		})
	}
	if value, ok := nu.mutation.CreatedAt(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: notes.FieldCreatedAt,
		})
	}
	if nu.mutation.AuthorCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   notes.AuthorTable,
			Columns: []string{notes.AuthorColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeUUID,
					Column: user.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := nu.mutation.AuthorIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   notes.AuthorTable,
			Columns: []string{notes.AuthorColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeUUID,
					Column: user.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, nu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{notes.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{err.Error(), err}
		}
		return 0, err
	}
	return n, nil
}

// NotesUpdateOne is the builder for updating a single Notes entity.
type NotesUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *NotesMutation
}

// SetTitle sets the "title" field.
func (nuo *NotesUpdateOne) SetTitle(s string) *NotesUpdateOne {
	nuo.mutation.SetTitle(s)
	return nuo
}

// SetBody sets the "body" field.
func (nuo *NotesUpdateOne) SetBody(s string) *NotesUpdateOne {
	nuo.mutation.SetBody(s)
	return nuo
}

// SetSlug sets the "slug" field.
func (nuo *NotesUpdateOne) SetSlug(s string) *NotesUpdateOne {
	nuo.mutation.SetSlug(s)
	return nuo
}

// SetTags sets the "tags" field.
func (nuo *NotesUpdateOne) SetTags(s []string) *NotesUpdateOne {
	nuo.mutation.SetTags(s)
	return nuo
}

// SetCreatedAt sets the "created_at" field.
func (nuo *NotesUpdateOne) SetCreatedAt(t time.Time) *NotesUpdateOne {
	nuo.mutation.SetCreatedAt(t)
	return nuo
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (nuo *NotesUpdateOne) SetNillableCreatedAt(t *time.Time) *NotesUpdateOne {
	if t != nil {
		nuo.SetCreatedAt(*t)
	}
	return nuo
}

// SetAuthorID sets the "author" edge to the User entity by ID.
func (nuo *NotesUpdateOne) SetAuthorID(id uuid.UUID) *NotesUpdateOne {
	nuo.mutation.SetAuthorID(id)
	return nuo
}

// SetNillableAuthorID sets the "author" edge to the User entity by ID if the given value is not nil.
func (nuo *NotesUpdateOne) SetNillableAuthorID(id *uuid.UUID) *NotesUpdateOne {
	if id != nil {
		nuo = nuo.SetAuthorID(*id)
	}
	return nuo
}

// SetAuthor sets the "author" edge to the User entity.
func (nuo *NotesUpdateOne) SetAuthor(u *User) *NotesUpdateOne {
	return nuo.SetAuthorID(u.ID)
}

// Mutation returns the NotesMutation object of the builder.
func (nuo *NotesUpdateOne) Mutation() *NotesMutation {
	return nuo.mutation
}

// ClearAuthor clears the "author" edge to the User entity.
func (nuo *NotesUpdateOne) ClearAuthor() *NotesUpdateOne {
	nuo.mutation.ClearAuthor()
	return nuo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (nuo *NotesUpdateOne) Select(field string, fields ...string) *NotesUpdateOne {
	nuo.fields = append([]string{field}, fields...)
	return nuo
}

// Save executes the query and returns the updated Notes entity.
func (nuo *NotesUpdateOne) Save(ctx context.Context) (*Notes, error) {
	var (
		err  error
		node *Notes
	)
	if len(nuo.hooks) == 0 {
		if err = nuo.check(); err != nil {
			return nil, err
		}
		node, err = nuo.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*NotesMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			if err = nuo.check(); err != nil {
				return nil, err
			}
			nuo.mutation = mutation
			node, err = nuo.sqlSave(ctx)
			mutation.done = true
			return node, err
		})
		for i := len(nuo.hooks) - 1; i >= 0; i-- {
			if nuo.hooks[i] == nil {
				return nil, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = nuo.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, nuo.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX is like Save, but panics if an error occurs.
func (nuo *NotesUpdateOne) SaveX(ctx context.Context) *Notes {
	node, err := nuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (nuo *NotesUpdateOne) Exec(ctx context.Context) error {
	_, err := nuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (nuo *NotesUpdateOne) ExecX(ctx context.Context) {
	if err := nuo.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (nuo *NotesUpdateOne) check() error {
	if v, ok := nuo.mutation.Title(); ok {
		if err := notes.TitleValidator(v); err != nil {
			return &ValidationError{Name: "title", err: fmt.Errorf("ent: validator failed for field \"title\": %w", err)}
		}
	}
	if v, ok := nuo.mutation.Body(); ok {
		if err := notes.BodyValidator(v); err != nil {
			return &ValidationError{Name: "body", err: fmt.Errorf("ent: validator failed for field \"body\": %w", err)}
		}
	}
	if v, ok := nuo.mutation.Slug(); ok {
		if err := notes.SlugValidator(v); err != nil {
			return &ValidationError{Name: "slug", err: fmt.Errorf("ent: validator failed for field \"slug\": %w", err)}
		}
	}
	return nil
}

func (nuo *NotesUpdateOne) sqlSave(ctx context.Context) (_node *Notes, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   notes.Table,
			Columns: notes.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeUUID,
				Column: notes.FieldID,
			},
		},
	}
	id, ok := nuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "ID", err: fmt.Errorf("missing Notes.ID for update")}
	}
	_spec.Node.ID.Value = id
	if fields := nuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, notes.FieldID)
		for _, f := range fields {
			if !notes.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != notes.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := nuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := nuo.mutation.Title(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: notes.FieldTitle,
		})
	}
	if value, ok := nuo.mutation.Body(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: notes.FieldBody,
		})
	}
	if value, ok := nuo.mutation.Slug(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: notes.FieldSlug,
		})
	}
	if value, ok := nuo.mutation.Tags(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeJSON,
			Value:  value,
			Column: notes.FieldTags,
		})
	}
	if value, ok := nuo.mutation.CreatedAt(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: notes.FieldCreatedAt,
		})
	}
	if nuo.mutation.AuthorCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   notes.AuthorTable,
			Columns: []string{notes.AuthorColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeUUID,
					Column: user.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := nuo.mutation.AuthorIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   notes.AuthorTable,
			Columns: []string{notes.AuthorColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeUUID,
					Column: user.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Notes{config: nuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, nuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{notes.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{err.Error(), err}
		}
		return nil, err
	}
	return _node, nil
}
