// Code generated by entc, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Notes is the predicate function for notes builders.
type Notes func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
